### ISSUE TITLE
Simplify page design of Reservation Manager and Space Designer page

### ISSUE THREAD

**Issue by msrivastav13** [trailheadapps/easy-spaces-lwc#153]
**What is missing from the application? Please describe.**
Currently, the page architecture for the reservation page and the space designer is pretty complex and hard to understand. We have been running with this app to the SI partners to showcase the app and have overwhelmed our learners by the app complexity.

Also, we have received some more feedback from flow product owners on how complex the design is.

**Current Design State** 

<img width="1730" alt="Screen Shot 2020-08-10 at 5 33 27 PM" src="https://user-images.githubusercontent.com/2276156/89833994-fcd53b00-db2f-11ea-92ad-84646bf5ff02.png">

The current design uses lwc, aura, and flows. Flows use lwc embedded in them. 

At this point, we are not able to get rid of aura because lwc currently does not support launching flows dynamically. This makes the design complex!

**Describe the solution you'd like**

We should get rid of the aura completely. This will simplify the design! 

What about the dynamic flow launch if we get rid of aura? 

For this, the proposal is we use the lightning app builder which allows us to select the flow component. This way we can still show how one could replace the different flow if needed.

<img width="1787" alt="Screen Shot 2020-08-10 at 5 41 53 PM" src="https://user-images.githubusercontent.com/2276156/89834438-da8fed00-db30-11ea-87ba-c14562c6d817.png">

proposed state

<img width="1698" alt="Screen Shot 2020-08-10 at 5 48 12 PM" src="https://user-images.githubusercontent.com/2276156/89835027-e9c36a80-db31-11ea-91f9-d25f91ce0c5e.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by msrivastav13** [comment]
@pozil and @adityanaag3 let us set some time to discuss this! IMHO we can simplify the page design to ease understanding for the developers. I have been working on the Trailhead badge and feel we need to pay attention to this enhancement.

**Comment by pozil** [comment]
Great suggestion, I like that idea @msrivastav13. I'm all in for simplicity and less code to maintain.

@muenzpraeger would that have any side effect on existing material?

**Comment by muenzpraeger** [comment]
The dynamic flow launch, based on user interaction, is one of the key Flow components in that app. FYI @zaynelt

**Comment by msrivastav13** [comment]
@muenzpraeger current code does not really show this! The flow that is launched is hard coded!

Also IMHO one can have the decision tree to launch a subflow within the flow logic itself and that would be less maintenance and more configurable!

Having an aura component just to launch a dynamic flow seems to be an overkill at this point!
