### ISSUE TITLE
[222+] Migration Aura Flow wrapper to LWC

### ISSUE THREAD

**Issue by muenzpraeger** [trailheadapps/easy-spaces-lwc#20]
**What is missing from the application? Please describe.**
Currently the application uses an Aura component for wrapping LWCs that are used in Flow (see [here](https://github.com/trailheadapps/easy-spaces-lwc/tree/develop/es-space-mgmt/main/default/aura/customerDetails) and [here](https://github.com/trailheadapps/easy-spaces-lwc/tree/develop/es-space-mgmt/main/default/aura/designFormCmp)).

**Describe the solution you'd like**
Once the new metadata target is available for flow screens the wrapper should be removed.

**Comment by adityanaag3** [comment]
Updated metadata target in Lightning Web Components, and updated the flows to directly use LWCs instead of Aura Wrappers. Refer to PR #47
