### ISSUE TITLE
Add instructions for deploying to Trailhead playground

### ISSUE THREAD

**Issue by sergeiwallace** [trailheadapps/easy-spaces-lwc#206]
**What is missing from the application? Please describe.**
A clear and concise description of what the problem is. Ex. I'd like to see an implementation of [...]

**Describe the solution you'd like**
Add instructions for deploying to Trailhead playground. the other sample apps have it but this one just has push for scratch orgs.

**Describe alternatives you've considered**

**Additional context**

**Comment by sergeiwallace** [comment]
I think this works: `sfdx force:source:deploy -p es-base-code,es-base-objects,es-base-styles,es-space-mgmt`

**Comment by msrivastav13** [comment]
@sergeiwallace We have instructions and recommend you use unlocked package for same.

https://github.com/trailheadapps/easy-spaces-lwc#installing-easy-spaces-using-unlocked-packages

Let me know if this does not work and why you would go by running the source deploy command?

**Comment by sergeiwallace** [comment]
Ah, I see. Sorry, missed that.
